CREATE TABLE USERS (
	ID INTEGER NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR2(255) NOT NULL,
  HASH VARCHAR2(255),
	ADMIN char(1) DEFAULT 0,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP,
	PRIMARY KEY (ID)
);

INSERT INTO USERS (
    ID, NAME, EMAIL, PASSWORD, ADMIN, CREATED_AT
  ) VALUES (
      (SELECT NVL(MAX(ID), 0) + 1 FROM USERS)
    , "New User"
    , "test@test.com"
    , "test"
    , 1
    , LOCALTIMESTAMP
  );